package product.api.kafka.event

import groovy.transform.Canonical

@Canonical
class ProductCreatedEvent {
    String eventType = "PRODUCT_CREATED"
    Long productId          // will be null on creation (generated by DB)
    String name
    String description
    BigDecimal price
    String timestamp
}
